before:
  hooks:
    - go mod tidy
builds:
  - id: passager
    main: ./cmd/passager
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
  # Cross compiling macOS-to-linux using musl-cross
  - id: passager_cross
    main: ./cmd/passager
    env:
      - CGO_ENABLED=1
      - CC=x86_64-linux-musl-gcc
    goos:
      - linux
    goarch:
      - amd64
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
